apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app-deployment
  namespace: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: 822127611269.dkr.ecr.ap-south-1.amazonaws.com/python_app_repo:latest
        ports:
        - containerPort: 5000
